#- name: install sudo via apt
#  apt:
#    name: sudo

- name: create group for ssh users
  become: true
  group:
    name: sshusers

- name: create group for su users
  become: true
  group:
    name: suusers

- name: create group for sudo users
  become: true
  group:
    name: sudousers

#- name: create new user ("{{user_name}}") with password, add to groups
#  user:
#    name: "{{ user_name }}"
#    password: "{{ user_pw | password_hash('sha512') }}"
#    #groups: "sshusers, sudousers" #suusers"
#    # sets the default shell for this user
#    shell: /bin/bash
- name: add user {{ user_name }} to relevant groups
  become: true
  ansible.builtin.user: 
    name: "{{ user_name }}"
    groups: "sshusers, sudousers, suusers"
    shell: /bin/bash
    append: yes

- name: limit sudo to sudousers groups
  become: true
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudousers'
    line: '%sudousers   ALL=(ALL:ALL) ALL'

- name: limit who can use su
  become: true
  register: sustd
  shell: |
    sudo dpkg-statoverride --update --add root suusers 4750 /bin/su
  failed_when:
    - sustd.rc != 0
    - '"exist" not in sustd.stderr' # todo: has to be changed

#- name: passwordless sudo for new user
#  lineinfile:
#    path: /etc/sudoers
#    regexp: '^{{ user_name }}'
#    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
#    state: present
#    mode: 0440
#    create: yes
#    validate: 'visudo -cf %s'

#- name: add authorized keys for new user
#  authorized_key:
#    user: "{{ user_name }}"
#    key: "{{ lookup('file', sshpub_location) }}"